line-length = 100
indent-width = 4
target-version = "py39"

[lint]
select = ["E", "F", "B", "I"]
ignore = []

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"